import {useState} from "react";
import {nativeLibraries,type NativeLibrary,type NativeCatalogEntry} from "../api/nativeLibraries";
export default function AnimeDubEditor({library,entry,onSaved}:{library:NativeLibrary;entry:NativeCatalogEntry;onSaved:()=>void}){
 const [cast,setCast]=useState<Record<string,unknown>[]>(()=>((entry.metadata.voice_cast??[]) as Record<string,unknown>[]).map(p=>({...p})));
 const [saving,setSaving]=useState(false),[error,setError]=useState("");
 function update(index:number,field:string,value:string){setCast(current=>current.map((p,i)=>i===index?{...p,[field]:value.trim()?value:null}:p));}
 async function save(){setSaving(true);setError("");try{const result=await nativeLibraries.editItem(library.id,entry,{voice_cast:cast});if(result.warnings.length)setError(result.warnings.join(" "));else onSaved();}catch(e){setError((e as Error).message);}finally{setSaving(false);}}
 const input="mt-1 w-full rounded-lg border border-border bg-input px-3 py-2 text-sm";
 return <div className="space-y-4 p-6"><p className="text-sm text-muted">Label the dub edition for each character credit. Blank editions remain unspecified. Manual cast edits are preserved during provider refreshes and saved to NFO when enabled.</p><div className="max-h-[60vh] space-y-3 overflow-y-auto">{cast.map((person,index)=><section key={index} className="rounded-xl border border-border p-3"><p className="text-sm font-medium">{String(person.name??"")} · {String(person.role??"")}</p><p className="text-xs text-muted">{String(person.language??"Unknown language")}</p><div className="mt-2 grid gap-3 sm:grid-cols-2"><label className="text-xs">Dub edition<input aria-label={`Dub edition for ${person.name} as ${person.role}`} className={input} value={String(person.dub_group??"")} placeholder="Unspecified dub" maxLength={120} onChange={e=>update(index,"dub_group",e.target.value)}/></label><label className="text-xs">Role notes<input aria-label={`Role notes for ${person.name} as ${person.role}`} className={input} value={String(person.role_notes??"")} maxLength={250} onChange={e=>update(index,"role_notes",e.target.value)}/></label></div></section>)}</div>{error&&<p role="alert" className="text-sm text-danger">{error}</p>}<button disabled={saving||!cast.length} className="rounded-lg bg-accent px-4 py-2 text-sm text-black disabled:opacity-50" onClick={()=>void save()}>{saving?"Saving…":"Save dub credits"}</button></div>;
}
