import {RefreshCw, Download, RotateCcw} from "lucide-react";
import {useState} from "react";
import {useMutation,useQuery,useQueryClient} from "@tanstack/react-query";
import {api} from "../api/client";
import {defaultServerSync,nativeLibraries,type ServerSyncOptions} from "../api/nativeLibraries";
import {Switch} from "./ui";
const INPUT="mt-2 w-full rounded-xl border border-edge bg-base px-3 py-2.5 text-sm text-white";
const BUTTON="rounded-xl border border-edge px-3 py-2 text-sm text-muted hover:bg-base disabled:opacity-50";
const fields:Record<string,string>={title:"Title",originaltitle:"Original title",sorttitle:"Sort title",year:"Year",identifiers:"Provider IDs",plot:"Description",tagline:"Tagline",rating:"Community rating",mpaa:"Content rating",premiered:"Release date",status:"Status",genres:"Genres",tags:"Tags",studios:"Studios",credits:"Cast and crew",season:"Season number",episode:"Episode number",runtime:"Runtime"};
export default function ConnectedServerSync({value=defaultServerSync,onChange,library}:{value?:ServerSyncOptions;onChange:(value:ServerSyncOptions)=>void;library?:string}){
 const servers=useQuery({queryKey:["servers"],queryFn:api.listServers});
 const libraries=useQuery({queryKey:["libraries",value.server_id],queryFn:()=>api.getLibraries(value.server_id!),enabled:!!value.server_id});
 const update=(patch:Partial<ServerSyncOptions>)=>onChange({...value,...patch});
 return <section className="space-y-4 rounded-2xl border border-edge p-5"><h3 className="font-semibold">Connected Server Sync</h3>
 <div className="flex items-center justify-between gap-4"><span>Override locked metadata<p className="text-xs text-muted">Allow incoming shared values to replace locked fields.</p></span><Switch label="Override locked metadata" checked={value.override_locked} onChange={()=>update({override_locked:!value.override_locked})}/></div>
 <div className="flex items-center justify-between gap-4"><span>Enable connected-server sync</span><Switch label="Enable connected-server sync" checked={value.enabled} onChange={()=>update({enabled:!value.enabled})}/></div>
 <label className="block text-sm text-muted">Sync source and recovery server<select aria-label="Sync source server" className={INPUT} value={value.server_id??""} onChange={e=>update({server_id:Number(e.target.value)||null,library_id:""})}><option value="">Select server</option>{servers.data?.map(server=><option key={server.id} value={server.id} disabled={server.type==="plex"}>{server.name}{server.type==="plex"?" · metadata sync unavailable":""}</option>)}</select></label>
 <label className="block text-sm text-muted">Server library<select aria-label="Sync source library" className={INPUT} disabled={!value.server_id} value={value.library_id} onChange={e=>update({library_id:e.target.value})}><option value="">Select library</option><option value="*">All matching libraries</option>{libraries.data?.map(lib=><option key={lib.id} value={lib.id}>{lib.title}</option>)}</select></label>
 {(servers.error||libraries.error)&&<p role="alert" className="text-danger text-sm">{(servers.error||libraries.error)?.message}</p>}
 <div className="flex items-center justify-between gap-4"><span>Push changes to all connected servers</span><Switch label="Push changes to all connected servers" checked={value.push_to_all} onChange={()=>update({push_to_all:!value.push_to_all})}/></div>
 {!value.push_to_all&&<fieldset className="space-y-2"><legend className="mb-2 text-sm text-muted">Additional push destinations</legend>{servers.data?.filter(s=>s.id!==value.server_id).map(server=><label key={server.id} className="flex items-center gap-3 text-sm"><input type="checkbox" checked={value.push_server_ids.includes(server.id)} onChange={e=>update({push_server_ids:e.target.checked?[...value.push_server_ids,server.id]:value.push_server_ids.filter(id=>id!==server.id)})}/>{server.name}{server.type==="plex"?" · static artwork uploads only":""}</label>)}</fieldset>}
 <div className="flex items-center justify-between gap-4"><span>Write synced metadata to NFO files<p className="text-xs text-muted">Merge shared fields; preserve custom XML and enhanced fields.</p></span><Switch label="Write synced metadata to NFO files" checked={value.write_nfo} onChange={()=>update({write_nfo:!value.write_nfo})}/></div>
 <p className="text-xs text-muted">Save library settings to apply. The source server supplies initial values and uncertain offline conflicts. Static artwork and shared metadata sync; animations and enhanced data stay local. Changes are checked every 30 seconds. Plex destinations receive supported static artwork uploads only.</p>
 {library&&<SyncActions library={library}/>}
 </section>;
}
export function SyncActions({library, menu=false}:{library:string;menu?:boolean}){
 const client=useQueryClient();
 const status=useQuery({queryKey:["native-sync",library],queryFn:()=>nativeLibraries.syncStatus(library),refetchInterval:5000});
 const [showImport,setShowImport]=useState(false),[selected,setSelected]=useState(Object.keys(fields)),[override,setOverride]=useState(false),[nfo,setNfo]=useState(false);
 const sync=useMutation({mutationFn:(input:Record<string,unknown>)=>nativeLibraries.sync(library,input),onSuccess:()=>{setShowImport(false);void client.invalidateQueries({queryKey:["native-sync",library]});void client.invalidateQueries({queryKey:["native-catalog",library]});}});
 const busy=sync.isPending||status.data?.status==="syncing"||status.data?.status==="queued";
 return <div className="space-y-3 border-t border-edge pt-4"><p className="text-xs text-muted">{status.data?.enabled?`Sync: ${({paused:"Automatic retries paused",retry_wait:"Waiting to retry"} as Record<string,string>)[status.data.status]??(status.data.status||"Waiting")} · ${status.data.pending} pending · ${status.data.matched} matched · ${status.data.unmatched} unmatched · ${status.data.failed} failed`:"Sync disabled"}</p>{status.data?.last_success&&<p className="text-xs text-muted">Last success: {new Date(status.data.last_success).toLocaleString()}</p>}
 {status.data?.status==="paused"&&<p role="status" className="text-sm text-muted">Automatic sync paused after three unsuccessful attempts. Review Sync notices, then use Sync now to retry. Completed import items are preserved.</p>}
 {status.data?.retry_at&&<p className="text-xs text-muted">Next retry: {new Date(status.data.retry_at).toLocaleString()}</p>}
 <div className={menu?"flex flex-col gap-2":"flex flex-wrap gap-2"}><button className={`${BUTTON} flex items-center justify-between gap-2`} disabled={busy||!status.data?.enabled} onClick={()=>sync.mutate({})}>Sync now<RefreshCw className="size-4"/></button><button className={`${BUTTON} flex items-center justify-between gap-2`} disabled={busy||!status.data?.enabled} onClick={()=>setShowImport(!showImport)}>Import metadata<Download className="size-4"/></button><button className={`${BUTTON} flex items-center justify-between gap-2`} disabled={busy||!status.data?.enabled} onClick={()=>{if(window.confirm("Restore shared metadata and static artwork from the source server? Pending outgoing edits will be discarded. Enhanced data and animations will remain."))sync.mutate({recover:true});}}>Restore server values<RotateCcw className="size-4"/></button></div>
 {showImport&&<div className="space-y-4 rounded-xl border border-edge bg-base p-4"><h4 className="font-semibold">Import server metadata</h4><div className="flex items-center justify-between"><span className="text-sm">Override locked metadata</span><Switch label="Import: Override locked metadata" checked={override} onChange={()=>setOverride(!override)}/></div><div className="space-y-4">{Object.entries({Identification:["title","originaltitle","sorttitle","year","identifiers"],"Descriptions and ratings":["plot","tagline","rating","mpaa","premiered","status"],Categories:["genres","tags","studios"],People:["credits"],"Series and episodes":["season","episode","runtime"]}).map(([group,keys])=><fieldset key={group} className="rounded-xl border border-edge p-3"><legend className="px-2 text-sm font-medium">{group}</legend><div className="grid gap-3 sm:grid-cols-2">{keys.map(field=><label key={field} className="flex items-center gap-2 text-sm text-muted"><input type="checkbox" checked={selected.includes(field)} onChange={e=>setSelected(e.target.checked?[...selected,field]:selected.filter(f=>f!==field))}/>{fields[field]}</label>)}</div></fieldset>)}</div><div className="flex items-center justify-between"><span className="text-sm">Write imported metadata to NFO files</span><Switch label="Import: Write NFO files" checked={nfo} onChange={()=>setNfo(!nfo)}/></div><p className="text-xs text-muted">Selected shared fields replace existing unlocked values. Unchecked fields and enhanced metadata remain unchanged.</p><button className={BUTTON} disabled={busy||!selected.length} onClick={()=>sync.mutate({fields:selected,override_locked:override,write_nfo:nfo})}>Import selected fields</button></div>}
 {(sync.error||status.error)&&<p role="alert" className="text-danger text-sm">{(sync.error||status.error)?.message}</p>}
 {!!status.data?.notices.length&&<details className="text-xs text-muted"><summary>Sync notices</summary>{status.data.notices.map((message,i)=><p key={i}>{message}</p>)}</details>}
 {!!status.data?.activity.length&&<details className="text-xs text-muted"><summary>Recent sync activity</summary>{status.data.activity.map((message,i)=><p key={i}>{message}</p>)}</details>}
 </div>;
}
