import {useState} from "react";
import {Database,Loader2} from "lucide-react";
import {nativeLibraries,type NativeLibrary,type NativeCatalogEntry} from "../api/nativeLibraries";
const names:Record<string,string>={mangadex:"MangaDex",comicvine:"ComicVine",anilist:"AniList",mal:"MyAnimeList"};
const labels:Record<string,string>={characters:"Characters",title:"Title",originaltitle:"Original title",plot:"Description",year:"Display year",volumes:"Display volume count",chapters:"Chapters",publisher:"Publisher",status:"Status",country:"Country",genres:"Genres",tags:"Tags",original_year:"Original release year",original_volumes:"Original volume count",edition_year:"Edition publication year",edition_volumes:"Edition volume count"};
const display=(value:unknown)=>value==null||value===""?"Empty":Array.isArray(value)?value.map(item=>typeof item==="object"&&item!==null&&"name" in item?String(item.name):String(item)).join(", "):String(value);
export default function FetchBookMetadata({library,entry,busy,onSaved}:{library:NativeLibrary;entry:NativeCatalogEntry;busy:boolean;onSaved:()=>void}){
 const providers=library.options?.metadata_providers?.book_series??["comicvine","anilist","mal"];
 const [provider,setProvider]=useState(providers.find(p=>entry.metadata.identifiers&& (entry.metadata.identifiers as Record<string,unknown>)[p])??providers[0]??"");
 const [fields,setFields]=useState<Record<string,unknown>>({}),[choices,setChoices]=useState<Record<string,{value:unknown;provider:string}>>({});
 const [previews,setPreviews]=useState<Record<string,Record<string,unknown>>>({});
 const [loading,setLoading]=useState(false),[saving,setSaving]=useState(false),[error,setError]=useState("");
 async function fetchFields(source=provider){setLoading(true);setError("");try{const result=await nativeLibraries.metadataPreview(library.id,entry.id,source);setFields(result.fields);setPreviews(current=>({...current,[source]:result.fields}));setChoices(current=>{const next={...current};for(const [key,value] of Object.entries(result.fields))if(entry.metadata[key]==null||entry.metadata[key]==="")next[key]??={value,provider:source};return next;});}catch(e){setError((e as Error).message);}finally{setLoading(false);}}
 async function apply(){setSaving(true);setError("");try{const values=Object.fromEntries(Object.entries(choices).map(([key,choice])=>[key,choice.value]));const sources={...(entry.metadata.book_provider_sources as Record<string,string>??{}),...Object.fromEntries(Object.entries(choices).map(([key,choice])=>[key,choice.provider]))};const result=await nativeLibraries.editItem(library.id,entry,{...values,book_provider_sources:sources});if(result.warnings.length)setError(result.warnings.join(" "));else onSaved();}catch(e){setError((e as Error).message);}finally{setSaving(false);}}
 return <div className="flex h-full min-h-0 flex-col"><div className="min-h-0 flex-1 space-y-5 overflow-y-auto px-6 pb-5 sm:px-8">
 <p className="text-sm text-muted">Fetch using the series IDs saved in Identify. Empty fields are selected automatically. Check populated fields only when you want to replace them. Artwork stays separate.</p>
 <div className="flex flex-wrap items-center justify-between gap-3"><div role="tablist" aria-label="Metadata providers" className="flex flex-wrap gap-2">{providers.map((p,index)=><button key={p} type="button" role="tab" id={`metadata-tab-${p}`} aria-selected={provider===p} aria-controls="metadata-provider-panel" tabIndex={provider===p?0:-1} disabled={loading||saving} onClick={()=>{setProvider(p);setError("");setFields(previews[p]??{});if(!previews[p])void fetchFields(p);}} onKeyDown={event=>{let next=index;if(event.key==="ArrowRight")next=(index+1)%providers.length;else if(event.key==="ArrowLeft")next=(index+providers.length-1)%providers.length;else if(event.key==="Home")next=0;else if(event.key==="End")next=providers.length-1;else return;event.preventDefault();const target=event.currentTarget.parentElement?.querySelectorAll<HTMLButtonElement>('[role="tab"]')[next];target?.click();target?.focus();}} className={`rounded-full border px-3 py-2 text-sm disabled:opacity-50 ${provider===p?"border-accent bg-accent/15 text-accent":"border-border text-muted hover:text-white"}`}>{names[p]??p}</button>)}</div><button onClick={()=>void fetchFields()} disabled={!provider||loading||saving} className="flex items-center gap-2 rounded-lg border border-border px-4 py-2 text-sm disabled:opacity-50">{loading?<Loader2 className="size-4 animate-spin"/>:<Database className="size-4"/>}{previews[provider]?"Refresh":"Fetch"}</button></div>
 {!providers.length&&<p className="text-sm text-muted">Enable book metadata providers in the library settings first.</p>}
 <p className="text-xs text-muted">Current includes pending selections from every tab. Nothing is saved until you apply the selected fields.</p>
 <p className="text-xs text-faint">AniList and MyAnimeList describe the original series. ComicVine describes the selected publication edition. Display year and volume count control the visible series pills; original and edition values are stored separately.</p>
 {Object.keys(fields).length>0&&<section id="metadata-provider-panel" role="tabpanel" aria-labelledby={`metadata-tab-${provider}`} className="divide-y divide-border">{Object.entries(fields).map(([key,value])=>{const selected=choices[key];return <label key={key} className="block py-4"><span className="flex items-center gap-3"><input aria-label={`Apply ${labels[key]??key}`} type="checkbox" checked={selected?.provider===provider} disabled={saving} onChange={e=>setChoices(current=>{const next={...current};if(e.target.checked)next[key]={value,provider};else delete next[key];return next;})} className="size-4 accent-accent"/><span className="text-sm font-semibold">{labels[key]??key}</span>{selected&&<span className="ml-auto text-xs text-accent">Selected: {names[selected.provider]}</span>}</span><span className="mt-2 grid gap-3 pl-7 sm:grid-cols-2"><span className="min-w-0 text-xs text-muted"><span className="mb-1 block text-faint">Current{selected?` · Pending ${names[selected.provider]}`:""}</span><span className="block max-h-40 overflow-y-auto whitespace-pre-wrap break-words">{display(selected?selected.value:entry.metadata[key])}</span></span><span className="min-w-0 text-xs"><span className="mb-1 block text-faint">{names[provider]}</span><span className="block max-h-40 overflow-y-auto whitespace-pre-wrap break-words">{display(value)}</span></span></span></label>;})}</section>}
 {error&&<p role="alert" className="text-sm text-amber-300">{error}</p>}
 </div><footer className="flex flex-wrap items-center gap-3 bg-sidebar px-6 py-5 sm:px-8"><button onClick={()=>void apply()} disabled={busy||saving||loading||!Object.keys(choices).length} className="rounded-lg bg-accent px-4 py-2 text-sm font-medium text-black disabled:opacity-50">{saving?"Applying…":`Apply ${Object.keys(choices).length} selected fields`}</button><p className="text-xs text-muted">Selections from different providers can be applied together. Applied fields are protected from automatic replacement.{library.options?.save_nfo?" Saves to NFO.":" NFO saving is off."}</p></footer></div>;
}
