import { ArrowDown, ArrowUp } from "lucide-react";
import type { NativeLibraryOptions, NativeLibraryType } from "../api/nativeLibraries";

const INPUT = "mt-2 w-full rounded-xl border border-edge bg-base px-3 py-2.5 text-sm text-white disabled:cursor-not-allowed disabled:opacity-40";
const LANGUAGES = {en: "English", ja: "Japanese", fr: "French", de: "German", es: "Spanish", it: "Italian", pt: "Portuguese", ko: "Korean", zh: "Chinese"};
const COUNTRIES = {US: "United States", GB: "United Kingdom", JP: "Japan", CA: "Canada", AU: "Australia", FR: "France", DE: "Germany", ES: "Spain", IT: "Italy", BR: "Brazil", KR: "South Korea", CN: "China"};
const LABELS: Record<string, string> = {anilist: "AniList", tmdb: "TheMovieDb", tvdb: "TheTVDB", anidb: "AniDB", mal: "MyAnimeList", omdb: "The Open Movie Database", fanart: "FanArt", capture: "Image Capture"};
function Group({title, children}: {title: string; children: React.ReactNode}) {
  return <section className="space-y-4 rounded-2xl border border-edge p-4 sm:p-5"><h3 className="font-semibold text-white">{title}</h3>{children}</section>;
}
function Toggle({label, help, checked = false, disabled = false, onChange}: {label: string; help?: string; checked?: boolean; disabled?: boolean; onChange?: (value: boolean) => void}) {
  return <label className={`flex items-start justify-between gap-4 ${disabled ? "text-faint" : "text-muted"}`}><span><span className="block text-sm font-medium">{label}</span>{help && <span className="mt-1 block text-xs leading-relaxed">{help}</span>}{disabled && <span className="mt-1 block text-xs text-faint">Not yet available in PosterView</span>}</span><span className="relative mt-1 shrink-0"><input type="checkbox" role="switch" aria-label={label} disabled={disabled} checked={checked} onChange={e => onChange?.(e.target.checked)} className="peer sr-only" /><span aria-hidden="true" className="block h-6 w-10 rounded-full bg-white/20 transition-colors after:absolute after:left-1 after:top-1 after:size-4 after:rounded-full after:bg-white after:transition-transform peer-checked:bg-accent peer-checked:after:translate-x-4 peer-focus-visible:outline peer-focus-visible:outline-2 peer-focus-visible:outline-accent peer-disabled:cursor-not-allowed peer-disabled:opacity-40" /></span></label>;
}
function UnavailableSelect({label, value, help}: {label: string; value: string; help?: string}) {
  return <label className="block text-sm text-faint">{label}<select aria-label={label} disabled className={INPUT}><option>{value}</option></select><span className="mt-1 block text-xs">Not yet available in PosterView{help ? ` · ${help}` : ""}</span></label>;
}
function ProviderList({title, supported, unavailable, order, onChange}: {title: string; supported: string[]; unavailable: string[]; order: string[]; onChange: (order: string[]) => void}) {
  const move = (index: number, offset: number) => {const next = [...order]; [next[index], next[index + offset]] = [next[index + offset], next[index]]; onChange(next);};
  const rows = [...order, ...supported.filter(p => !order.includes(p)), ...unavailable];
  return <Group title={title}><p className="text-xs leading-relaxed text-muted">Enable sources and set their priority. Lower priority sources fill missing information. Use the arrows to reorder enabled sources.</p><ul className="divide-y divide-edge">{rows.map(provider => {
    const enabled = order.includes(provider), available = supported.includes(provider), index = order.indexOf(provider);
    return <li key={provider} className="flex items-center gap-3 py-3"><input aria-label={`${title}: ${LABELS[provider]}`} type="checkbox" disabled={!available} checked={enabled} className="size-5 accent-accent disabled:opacity-40" onChange={e => onChange(e.target.checked ? [...order, provider] : order.filter(p => p !== provider))} /><span className={`min-w-0 flex-1 text-sm ${available ? "text-white" : "text-faint"}`}>{LABELS[provider]}{!available && <span className="mt-1 block text-xs">Not yet available</span>}</span>{enabled && <div className="flex gap-1"><button type="button" disabled={index === 0} aria-label={`Move ${LABELS[provider]} up in ${title}`} className="rounded-lg p-2 text-muted hover:bg-base disabled:opacity-30" onClick={() => move(index, -1)}><ArrowUp className="size-4" /></button><button type="button" disabled={index === order.length - 1} aria-label={`Move ${LABELS[provider]} down in ${title}`} className="rounded-lg p-2 text-muted hover:bg-base disabled:opacity-30" onClick={() => move(index, 1)}><ArrowDown className="size-4" /></button></div>}</li>;
  })}</ul></Group>;
}
export default function NativeLibrarySettings({options, type, animeContent, section, onChange}: {options: NativeLibraryOptions; type: NativeLibraryType; animeContent: "both" | "shows" | "movies"; section: number; onChange: (options: NativeLibraryOptions) => void}) {
  const update = <K extends keyof NativeLibraryOptions>(key: K, value: NativeLibraryOptions[K]) => onChange({...options, [key]: value});
  const languages = (key: "metadata_language" | "image_language", label: string) => <label className="block text-sm text-muted">{label}<select aria-label={label} className={INPUT} value={options[key]} onChange={e => update(key, e.target.value)}>{Object.entries(LANGUAGES).map(([value, name]) => <option key={value} value={value}>{name}</option>)}</select></label>;
  const shows = type === "shows" || (type === "anime" && animeContent !== "movies");
  const movies = type === "movies" || (type === "anime" && animeContent !== "shows");
  const groups: [string, string][] = [...(movies ? [["movie", "Movie"] as [string,string]] : []), ...(shows ? [["series", "Series"] as [string,string], ["season", "Season"] as [string,string], ["episode", "Episode"] as [string,string]] : []), ...(type === "books" ? [["book_series", "Book series"] as [string,string]] : [])];
  const providerGroups = (images: boolean) => groups.map(([kind, name]) => {
    const supported = kind === "book_series" ? ["anilist", "mal"] : kind === "season" ? ["tmdb", "tvdb", ...(images ? ["fanart"] : [])] : kind === "episode" ? ["tmdb", "tvdb", "omdb", ...(type === "anime" && !images ? ["anidb"] : [])] : [ ...(type === "anime" ? ["anilist", "mal", "anidb"] : []), "tmdb", "tvdb", "omdb", ...(images ? ["fanart"] : [])];
    const defaults = supported.length ? [supported[0]] : [];
    const key = images ? "image_providers" : "metadata_providers";
    const unavailable = images && kind === "episode" ? ["capture"] : [];
    return <ProviderList key={kind} title={`${name} ${images ? "Image Fetchers" : "Metadata Downloaders"}`} supported={supported} unavailable={unavailable} order={options[key][kind] ?? defaults} onChange={order => update(key, {...options[key], [kind]: order})} />;
  });
  return <div className="space-y-5">
    {section === 2 && <><Group title="Library Settings">{languages("metadata_language", "Preferred metadata download language")}<p className="text-xs text-faint">TMDB uses this language. AniList supports English and Japanese titles; other metadata remains in its source language.</p><label className="block text-sm text-muted">Certification country<select aria-label="Certification country" className={INPUT} value={options.certification_country} onChange={e => update("certification_country", e.target.value)}>{Object.entries(COUNTRIES).map(([value,name]) => <option key={value} value={value}>{name}</option>)}</select><span className="mt-1 block text-xs text-faint">Selects the content rating returned by TMDB when available.</span></label>{languages("image_language", "Preferred image download language")}<Toggle label="Prefer embedded titles over filenames" help="Use embedded video titles when no local NFO title is available. Provider metadata can still identify the item." checked={options.prefer_embedded_titles} onChange={v => update("prefer_embedded_titles", v)} /><Toggle label="Enable real-time monitoring" checked={options.real_time_monitor} onChange={v => update("real_time_monitor", v)} help="Automatically scan changed media and metadata after a short delay. Network mounts also use polling." /><Toggle label="Exclude from global search" disabled /><Toggle label="Merge the contents of top-level folders in folder view" disabled /></Group><Group title="Ignore Files"><label className="block text-sm text-muted">Ignore files containing sample below (MB)<input aria-label="Ignore sample files below (MB)" type="number" min={0} max={10000} className={INPUT} value={options.sample_ignore_mb} onChange={e => update("sample_ignore_mb", Math.max(0, Math.min(10000, Number(e.target.value))))} /><span className="mt-1 block text-xs text-faint">Set to 0 to include samples. Backdrop folders are always excluded.</span></label><Toggle label="Support .plexignore files" disabled /></Group>{shows && <Group title="Automatic Grouping"><Toggle label="Automatically merge series spread across multiple folders" disabled /></Group>}</>}
    {section === 3 && <><Group title="Metadata Readers"><Toggle label="NFO reader" help="Read local NFO files before internet sources. Custom book fields are preserved." checked={options.read_nfo} onChange={v => update("read_nfo", v)} /></Group><Group title="Internet Metadata"><Toggle label="Fetch missing metadata and artwork" help="Local and manually edited values take priority. Provider credentials are configured in Search Providers. AniDB requires a local NFO anime ID and a registered HTTP client." checked={options.fetch_missing} onChange={v => update("fetch_missing", v)} /><Toggle label="Allow adult metadata" help="Allows internet identification of adult titles; existing local metadata is retained." checked={options.allow_adult_metadata} onChange={v => update("allow_adult_metadata", v)} /></Group>{providerGroups(false)}<Group title="Metadata Refresh"><UnavailableSelect label="Automatically refresh internet metadata after initial import" value="Never" /><UnavailableSelect label="Refresh episode placeholder titles such as TBA" value="Not enabled" /><p className="text-xs text-muted">Manual scans currently fill missing information and preserve populated fields.</p></Group><Group title="Metadata Savers"><Toggle label="NFO saver" help="Write metadata beside your media. Requires write permission; unknown XML fields are preserved." checked={options.save_nfo} onChange={v => update("save_nfo", v)} /></Group></>}
    {section === 4 && <><Group title="Local Artwork"><Toggle label="Use local artwork" help="Use supported artwork beside your media before image fetchers." checked={options.local_artwork} onChange={v => update("local_artwork", v)} /></Group>{providerGroups(true)}<Group title="Fetcher Settings"><p className="text-xs text-muted">Download one missing image per enabled type. Existing and manually uploaded artwork takes priority.</p>{["poster", "backdrop", "thumb", "logo", "banner"].map(kind => <Toggle key={kind} label={`Download ${kind}`} checked={options.image_types.includes(kind)} onChange={v => update("image_types", v ? [...options.image_types, kind] : options.image_types.filter(k => k !== kind))} />)}<UnavailableSelect label="Minimum image width" value="Provider default" /></Group><Group title="Artwork Storage"><Toggle label="Save artwork into media folders" checked={options.save_artwork} onChange={v => update("save_artwork", v)} help="Requires writable media folders. Saves poster.jpg, fanart.jpg, landscape.jpg, clearlogo.png, seasonNN-poster.jpg and episode filename.jpg. Manual uploads replace matching files; scans preserve existing local artwork." /><Toggle label="Keep a cached copy of local images" disabled /><Toggle label="Download images in advance" checked disabled help="Provider artwork is currently downloaded during scanning; lazy downloading is not implemented." /><p className="text-xs text-muted">Fetched and uploaded images stay in application data. Enable media-folder saving to also write compatible sidecar images beside your media.</p></Group></>}
    {section === 5 && <><Group title="Collections"><UnavailableSelect label="Minimum automatic collection size" value="Not enabled" /></Group><Group title="Chapters"><Toggle label="Generate chapters for videos without embedded chapters" disabled /></Group><Group title="Playback">{[["Minimum resume percentage", "2"], ["Maximum resume percentage", "90"], ["Minimum resume duration (seconds)", "120"]].map(([label,value]) => <label key={label} className="block text-sm text-faint">{label}<input aria-label={label} type="number" disabled value={value} className={INPUT} /><span className="mt-1 block text-xs">Not yet available · native video playback is not implemented</span></label>)}</Group></>}
  </div>;
}
