import ProviderConnection from "./ProviderConnection";
import { useEffect, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { apiRequest } from "../api/client";
interface Settings {mal_configured: boolean; omdb_configured: boolean; anidb_client: string; anidb_client_version: string;}
const INPUT="mt-2 w-full rounded-lg border border-edge bg-base px-3 py-2 text-sm text-white";
const BUTTON="rounded-full border border-border bg-input px-4 py-2 text-sm text-white hover:border-accent disabled:opacity-50";
export default function NativeProviderCredentials(){
  const client=useQueryClient();
  const config=useQuery({queryKey:["native-provider-settings"],queryFn:()=>apiRequest<Settings>("/native/providers/settings")});
  const [mal,setMal]=useState("");const [omdb,setOmdb]=useState("");const [anidb,setAnidb]=useState("");const [version,setVersion]=useState("");
  useEffect(()=>{if(config.data){setAnidb(config.data.anidb_client);setVersion(config.data.anidb_client_version);}},[config.data]);
  const save=useMutation({mutationFn:(provider:string)=>apiRequest<Settings>("/native/providers/settings",{method:"PUT",body:JSON.stringify(provider==="mal"?{mal_client_id:mal}:provider==="omdb"?{omdb_api_key:omdb}:{anidb_client:anidb,anidb_client_version:version})}),onSuccess:(_,provider)=>{if(provider==="mal")setMal("");if(provider==="omdb")setOmdb("");void client.invalidateQueries({queryKey:["native-provider-settings"]});void client.invalidateQueries({queryKey:["artwork-providers"]});}});
  const test=useMutation({mutationFn:(provider:string)=>apiRequest<{ok:boolean;message:string}>(`/native/providers/test/${provider}`,{method:"POST"})});
  const providers=[{id:"mal",name:"MyAnimeList",url:"https://myanimelist.net/apiconfig",help:"Official API client ID for anime and manga metadata and cover artwork. No account OAuth token is required for these public records.",configured:config.data?.mal_configured,ready:!!mal.trim()}, {id:"omdb",name:"OMDb",url:"https://www.omdbapi.com/apikey.aspx",help:"API key for movie, series, and episode metadata and poster images.",configured:config.data?.omdb_configured,ready:!!omdb.trim()}, {id:"anidb",name:"AniDB",url:"https://wiki.anidb.net/HTTP_API_Definition",help:"Enter your registered HTTP client name and numeric version. AniDB fills missing IDs from unique title matches during metadata scans, verifies year and media type, caches records for 24 hours, and limits requests. Episode lookup supports season 1 and specials; sequel seasons require separate anime identification.",configured:!!config.data?.anidb_client&&!!config.data?.anidb_client_version,ready:!!anidb.trim()&&!!version.trim()}];
  return <div>{config.error&&<p role="alert" className="text-sm text-danger">{config.error.message}</p>}{providers.map(provider=><ProviderConnection key={provider.id} id={provider.id} name={provider.name} description={provider.id==="mal"?"Anime and manga":provider.id==="omdb"?"Movies and TV":"Anime"} status={provider.configured?"Credentials saved":"Not configured"} setupUrl={provider.url}><p className="mt-2 text-xs leading-relaxed text-muted">{provider.help} <a href={provider.url} target="_blank" rel="noreferrer" className="text-accent underline">Provider setup</a></p>{provider.id==="anidb"?<div className="mt-3 grid gap-3 sm:grid-cols-2"><label className="text-xs text-muted">AniDB registered client name<input aria-label="AniDB registered client name" value={anidb} onChange={e=>setAnidb(e.target.value)} className={INPUT} autoComplete="off" /></label><label className="text-xs text-muted">AniDB client version<input aria-label="AniDB client version" type="number" min={1} value={version} onChange={e=>setVersion(e.target.value)} className={INPUT} /></label></div>:<label className="mt-3 block text-xs text-muted">{provider.name} {provider.id==="mal"?"Client ID":"API key"}<input type="password" autoComplete="off" value={provider.id==="mal"?mal:omdb} onChange={e=>provider.id==="mal"?setMal(e.target.value):setOmdb(e.target.value)} placeholder={provider.configured?"Saved credential":"Enter credential"} className={INPUT} /></label>}<div className="mt-3 flex flex-wrap gap-2"><button className={BUTTON} disabled={save.isPending||!provider.ready} onClick={()=>{test.reset();save.mutate(provider.id);}}>Save {provider.name}</button><button className={BUTTON} disabled={test.isPending||!provider.configured||save.isPending} onClick={()=>test.mutate(provider.id)}>Test {provider.name}</button></div>{save.variables===provider.id&&save.error&&<p role="alert" className="mt-2 text-xs text-danger">{save.error.message}</p>}{save.variables===provider.id&&save.isSuccess&&<p role="status" className="mt-2 text-xs text-accent">Settings saved.</p>}{test.variables===provider.id&&(test.isPending||test.data||test.error)&&<p role="status" className={`mt-2 text-xs ${test.error||test.data?.ok===false?"text-danger":"text-accent"}`}>{test.isPending?"Testing saved credentials…":test.error?.message||test.data?.message}</p>}</ProviderConnection>)}</div>;
}
