import AnimatedArtwork from "./AnimatedArtwork";
import NativeScanProgress from "./NativeScanProgress";
import { useEffect, useState } from "react";
import { createPortal } from "react-dom";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { RefreshCw, Trash2, X, ImagePlus, Plus } from "lucide-react";
import { nativeLibraries, type NativeLibrary, type NativeCatalogEntry } from "../api/nativeLibraries";
const BUTTON="rounded-xl border border-edge px-3 py-2 text-sm text-muted hover:bg-base hover:text-white disabled:opacity-50";
const INPUT="w-full rounded-xl border border-edge bg-base px-3 py-2 text-sm text-white focus:border-accent focus:outline-none";
const labels:Record<string,string>={title:"Title",originaltitle:"Original title",sorttitle:"Sort title",plot:"Overview",year:"Year",runtime:"Runtime (minutes)",genres:"Genres",tags:"Tags",studios:"Studios",edition:"Edition",volumes:"Volumes",status:"Status",season:"Season",episode:"Episode",rating:"Community rating"};
export default function NativeCatalogPanel({library,onClose,onDeleted,embedded=false}:{library:NativeLibrary;onClose:()=>void;onDeleted:()=>void;embedded?:boolean}){
 const client=useQueryClient();
 const status=useQuery({queryKey:["native-scan",library.id],queryFn:()=>nativeLibraries.status(library.id),refetchInterval:q=>q.state.data?.status==="scanning"?2000:false});
 const catalog=useQuery({queryKey:["native-catalog",library.id],queryFn:()=>nativeLibraries.catalog(library.id),refetchInterval:status.data?.status==="scanning"?5000:false});
 const [selected,setSelected]=useState<NativeCatalogEntry|null>(null),[filter,setFilter]=useState(""),[confirm,setConfirm]=useState(false);
 const busy=status.data?.status==="scanning";
 const scan=useMutation({mutationFn:()=>nativeLibraries.scan(library.id),onSuccess:()=>{void client.invalidateQueries({queryKey:["native-scan",library.id]});}});
 const remove=useMutation({mutationFn:()=>nativeLibraries.remove(library.id,library.revision),onSuccess:onDeleted});
 useEffect(()=>{if(status.data?.status&&status.data.status!=="scanning")void client.invalidateQueries({queryKey:["native-catalog",library.id]});},[status.data?.status,client,library.id]);
 useEffect(()=>{if(embedded)return;const previous=document.body.style.overflow;document.body.style.overflow="hidden";return()=>{document.body.style.overflow=previous;};},[embedded]);
 const visible=(catalog.data??[]).filter(e=>e.available&&(filter?e.title.toLowerCase().includes(filter.toLowerCase()):!e.parent_path));
 const updated=()=>{void client.invalidateQueries({queryKey:["native-catalog",library.id]});setSelected(null);};
 const panel = <div className={embedded ? "h-full" : "fixed inset-0 z-[85] flex items-center justify-center bg-black/70 backdrop-blur-sm sm:p-6"}><section role={embedded ? "region" : "dialog"} aria-modal={embedded ? undefined : true} aria-label={`${library.name} library`} className={embedded ? "flex h-full w-full flex-col overflow-hidden bg-panel" : "flex h-full w-full max-w-6xl flex-col overflow-hidden border border-edge bg-panel shadow-2xl sm:h-[90dvh] sm:rounded-2xl"}>
 <header className="flex flex-wrap items-center justify-between gap-3 border-b border-edge p-5"><div><h2 className="text-lg font-semibold text-white">{library.name}</h2><p className="mt-1 text-xs text-muted">Manual library · {catalog.data?.filter(e=>e.available).length??0} catalog items</p></div><div className="flex items-center gap-2"><button className={BUTTON} disabled={busy||scan.isPending||remove.isPending} onClick={()=>scan.mutate()}><RefreshCw className={`mr-2 inline size-4 ${busy?"animate-spin":""}`} />{busy?"Scanning…":"Scan library"}</button><button aria-label="Delete library" className={BUTTON} disabled={busy||remove.isPending} onClick={()=>setConfirm(true)}><Trash2 className="size-4" /></button>{!embedded&&<button aria-label="Close library" className={BUTTON} onClick={onClose}><X className="size-4" /></button>}</div></header>
 <main className="min-h-0 flex-1 overflow-y-auto p-5">
 {confirm&&<div role="alertdialog" aria-label="Delete library confirmation" className="mb-5 rounded-xl border border-danger/40 bg-base p-4"><h3 className="font-medium text-white">Delete {library.name}?</h3><p className="mt-2 text-sm text-muted">This removes the manual library and its catalog records. Media, NFO files, and local artwork stay on disk.</p><div className="mt-4 flex gap-2"><button className={BUTTON} disabled={remove.isPending} onClick={()=>setConfirm(false)}>Cancel</button><button className="rounded-xl bg-danger px-4 py-2 text-sm text-white disabled:opacity-50" disabled={remove.isPending} onClick={()=>remove.mutate()}>{remove.isPending?"Deleting…":"Delete library"}</button></div></div>}
 {(scan.error||remove.error||catalog.error||status.error)&&<p role="alert" className="mb-4 text-sm text-danger">{(scan.error||remove.error||catalog.error||status.error)?.message}</p>}
 {status.data&&<div className="mb-5 rounded-xl border border-edge bg-base p-4"><NativeScanProgress status={status.data} />{status.data.warnings.length>0&&<details className="mt-3 text-sm text-muted"><summary className="cursor-pointer">Review {status.data.warnings.length} scan notices</summary><ul className="mt-2 max-h-48 space-y-2 overflow-y-auto">{status.data.warnings.map((w,i)=><li key={i}>{w}</li>)}</ul></details>}</div>}
 {selected?<><button className={`${BUTTON} mb-4`} onClick={()=>setSelected(null)}>Back to library</button><EntryEditor key={selected.id} library={library} entry={selected} busy={!!busy} onSaved={updated} /><div className="mt-6 grid gap-2 sm:grid-cols-2">{catalog.data?.filter(e=>e.available&&e.parent_path===selected.path).map(e=><button key={e.id} className={`${BUTTON} text-left`} onClick={()=>setSelected(e)}>{e.title} · {e.kind}</button>)}</div></>:<>
 <input className={`${INPUT} mb-5 max-w-lg`} aria-label="Search catalog" placeholder="Search titles, including episodes…" value={filter} onChange={e=>setFilter(e.target.value)} />
 {catalog.isPending&&<p role="status" className="text-muted">Loading catalog…</p>}
 {!catalog.isPending&&visible.length===0&&<p className="py-8 text-center text-muted">{busy?"Items will appear when the scan finishes.":"No matching items. Scan the library to discover media."}</p>}
 <div className="grid grid-cols-2 gap-4 sm:grid-cols-3 lg:grid-cols-5">{visible.slice(0,250).map(entry=><button key={entry.id} className="overflow-hidden rounded-xl border border-edge bg-base text-left hover:border-accent" onClick={()=>setSelected(entry)}><div className="flex aspect-[2/3] items-center justify-center bg-panel">{entry.artwork.some(a=>a.kind==="poster")?<AnimatedArtwork className="h-full w-full object-cover" alt="" src={`${nativeLibraries.artworkUrl(library.id,entry.id,"poster")}?v=${entry.revision}&format=${entry.artwork.find(a=>a.kind==="poster")?.path.split(".").pop()}`} />:<ImagePlus className="size-8 text-faint" />}</div><div className="p-3"><p className="truncate text-sm font-medium text-white">{entry.title}</p><p className="mt-1 text-xs text-muted">{entry.kind.replaceAll("_"," ")}{!entry.available?" · Missing from disk":""}</p></div></button>)}</div>{visible.length>250&&<p className="mt-4 text-sm text-muted">Showing 250 results. Refine your search to find more.</p>}</>}
 </main></section></div>;
 return embedded ? panel : createPortal(panel,document.body);
}
export function EntryEditor({library,entry,busy,onSaved,dialog=false}:{library:NativeLibrary;entry:NativeCatalogEntry;busy:boolean;onSaved:()=>void;dialog?:boolean}){
 const [draft,setDraft]=useState<Record<string,unknown>>({...entry.metadata}),[notices,setNotices]=useState<string[]>([]),[artKind,setArtKind]=useState("poster");
 const save=useMutation({mutationFn:()=>nativeLibraries.editItem(library.id,entry,draft),onSuccess:result=>{if(result.warnings.length)setNotices(result.warnings);else onSaved();}});
 const upload=useMutation({mutationFn:(file:File)=>nativeLibraries.upload(library.id,entry.id,artKind,file),onSuccess:onSaved});
 const fields=[...new Set(["title","originaltitle","sorttitle","status","rating","plot","year","runtime","genres","tags","studios",...(entry.kind.startsWith("book")?["edition","volumes"]:[]),...Object.keys(entry.metadata).filter(k=>typeof entry.metadata[k]==="string"||typeof entry.metadata[k]==="number")])].filter(k=>!k.endsWith("_data")&&!k.startsWith('_')&&!['actor','director','writer','genre','tag','studio','anilistid','tmdbid','imdbid','tvdbid'].includes(k));
 const [newTerms,setNewTerms]=useState<Record<string,string>>({});
 const update=(key:string,value:unknown)=>setDraft(d=>({...d,[key]:value}));const identifiers=(draft.identifiers??{}) as Record<string,unknown>;const credits=Array.isArray(draft.credits)?draft.credits as Record<string,unknown>[]:[];
 const editorInput="w-full rounded border border-border bg-input px-3 py-2 text-sm text-white focus:border-accent focus:outline-none";
 return <div className={dialog?"flex h-full min-h-0 flex-col":"space-y-6"}><div className={dialog?"min-h-0 flex-1 space-y-8 overflow-y-auto px-6 pb-6 sm:px-10":"space-y-8"}><p className="break-all text-sm text-muted">{entry.path}</p>
 <section aria-label="Metadata fields"><div className="space-y-6">{fields.filter(field=>!["genres","tags","studios"].includes(field)).map(field=>{const array=["genres","tags","studios"].includes(field),value=draft[field],text=array?(Array.isArray(value)?value.join(", "):""):String(value??"");return <label key={field} className="block"><span className="mb-1 block text-sm text-muted">{labels[field]??field.replaceAll('_',' ')}</span>{field==="plot"?<textarea className={`${editorInput} min-h-32`} value={text} onChange={e=>update(field,e.target.value)} />:<input className={editorInput} value={text} onChange={e=>update(field,array?e.target.value.split(',').map(s=>s.trim()).filter(Boolean):["year","season","episode","runtime","volumes","rating"].includes(field)&&e.target.value?Number(e.target.value):e.target.value)} />}</label>;})}</div></section>
 <section><h4 className="mb-4 text-xl font-semibold text-white">External IDs</h4><p className="mb-3 text-xs text-muted">Add a confirmed provider ID when identification needs review, then scan again.</p><div className="space-y-6">{["anilist","tmdb","imdb","tvdb","mal","anidb"].map(provider=><label key={provider} className="block text-sm text-muted">{({anilist:"AniList",tmdb:"TheMovieDb",imdb:"IMDb",tvdb:"TheTVDB",mal:"MyAnimeList",anidb:"AniDB"} as Record<string,string>)[provider]} ID<input className={`${editorInput} mt-1`} value={String(identifiers[provider]??"")} onChange={e=>update("identifiers",{...identifiers,[provider]:e.target.value})} /></label>)}</div></section>
 {['genres','studios','tags'].map(field=>{const values=Array.isArray(draft[field])?draft[field] as string[]:[];return <section key={field}><h4 className="mb-4 text-xl font-semibold text-white">{labels[field]}</h4><div className="flex gap-2"><input aria-label={`Add ${field}`} className={editorInput} placeholder={`Add ${field==='genres'?'genre':field==='studios'?'studio':'tag'}`} value={newTerms[field]??""} onChange={e=>setNewTerms(current=>({...current,[field]:e.target.value}))} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();const value=newTerms[field]?.trim();if(value){update(field,[...new Set([...values,value])]);setNewTerms(current=>({...current,[field]:""}));}}}}/><button aria-label={`Add to ${field}`} className={BUTTON} disabled={!newTerms[field]?.trim()} onClick={()=>{update(field,[...new Set([...values,newTerms[field].trim()])]);setNewTerms(current=>({...current,[field]:""}));}}><Plus className="size-4"/></button></div><ul className="mt-3 divide-y divide-border">{values.map((value,index)=><li key={index} className="flex items-center justify-between gap-3 py-3 text-sm"><span>{value}</span><button aria-label={`Remove ${field}: ${value}`} className="rounded p-1 text-muted hover:text-white" onClick={()=>update(field,values.filter((_,i)=>i!==index))}><X className="size-4"/></button></li>)}</ul></section>;})}
 <section><h4 className="mb-4 text-xl font-semibold text-white">Cast and crew</h4><div className="max-h-72 space-y-2 overflow-y-auto">{credits.map((credit,index)=><div key={index} className="flex flex-wrap gap-2"><input aria-label={`Credit ${index+1} name`} className={`${INPUT} min-w-32 flex-1`} value={String(credit.name??"")} placeholder="Name" onChange={e=>update("credits",credits.map((c,i)=>i===index?{...c,name:e.target.value}:c))} /><input aria-label={`Credit ${index+1} role`} className={`${INPUT} min-w-32 flex-1`} value={String(credit.role??"")} placeholder="Role" onChange={e=>update("credits",credits.map((c,i)=>i===index?{...c,role:e.target.value}:c))} /><select aria-label={`Credit ${index+1} category`} className={`${INPUT} !w-auto`} value={String(credit.category??"cast")} onChange={e=>update("credits",credits.map((c,i)=>i===index?{...c,category:e.target.value}:c))}>{["cast","crew","voice","author","illustrator","narrator"].map(c=><option key={c}>{c}</option>)}</select><button aria-label={`Remove credit ${index+1}`} className={BUTTON} onClick={()=>update("credits",credits.filter((_,i)=>i!==index))}><X className="size-4" /></button></div>)}</div><button className={`${BUTTON} mt-3`} onClick={()=>update("credits",[...credits,{name:"",role:"",category:"cast"}])}>Add credit</button></section>
 {Array.isArray(draft.characters)&&draft.characters.length>0&&<section><h4 className="mb-4 text-xl font-semibold text-white">Characters</h4><ul className="max-h-64 space-y-2 overflow-y-auto">{(draft.characters as Record<string,unknown>[]).map((c,i)=><li key={i} className="text-sm text-muted"><span className="font-medium text-white">{String(c.name??"")}</span> · {String(c.role??"")}<p className="mt-1 line-clamp-3 text-xs">{String(c.biography??"")}</p></li>)}</ul></section>}
 <section><h4 className="mb-4 text-xl font-semibold text-white">Artwork</h4><div className="flex flex-wrap gap-3">{entry.artwork.map(a=><div key={a.kind} className="w-28"><AnimatedArtwork className="h-32 w-full rounded-lg bg-base object-contain" alt={a.kind} src={`${nativeLibraries.artworkUrl(library.id,entry.id,a.kind)}?v=${entry.revision}&format=${a.path.split(".").pop()}`} /><p className="mt-1 text-xs text-muted">{a.kind} · {a.source}</p></div>)}</div><div className="mt-4 flex flex-wrap items-center gap-3"><select className={`${INPUT} !w-auto`} aria-label="Artwork type" value={artKind} onChange={e=>setArtKind(e.target.value)}>{["poster","backdrop","banner","logo","thumb","landscape","disc"].map(k=><option key={k}>{k}</option>)}</select><label className={BUTTON}>{upload.isPending?"Uploading…":"Upload artwork"}<input type="file" accept="image/jpeg,image/png,image/webp,image/gif,video/webm" className="sr-only" disabled={busy||upload.isPending} onChange={e=>{const file=e.target.files?.[0];if(file)upload.mutate(file);}} /></label></div></section>
 {entry.files.length>0&&<section><h4 className="mb-4 text-xl font-semibold text-white">Media files</h4>{entry.files.map(f=><p key={f.path} className="break-all text-xs text-muted">{f.path} · {f.extension?.toUpperCase()} · {(f.size/1024/1024).toFixed(1)} MB{f.media_info?.format?.duration ? ` · ${Math.round(Number(f.media_info.format.duration) / 60)} min` : ""}{f.media_info?.streams?.map(stream => ` · ${String(stream.codec_type ?? "")} ${String(stream.codec_name ?? "")}${stream.width ? ` ${String(stream.width)}×${String(stream.height)}` : ""}`).join("")}</p>)}</section>}
 {(save.error||upload.error)&&<p role="alert" className="text-sm text-danger">{(save.error||upload.error)?.message}</p>}{notices.length>0&&<div role="alert" className="text-sm text-danger">{notices.map(n=><p key={n}>{n}</p>)}<button className={`${BUTTON} mt-3`} onClick={onSaved}>Return to library</button></div>}
 </div><footer className={dialog?"shrink-0 bg-sidebar px-6 py-5 sm:px-8":"pt-4"}><button className="w-full rounded-full bg-accent px-5 py-2.5 text-sm font-medium text-base disabled:opacity-50" disabled={busy||save.isPending||!String(draft.title??"").trim()} onClick={()=>save.mutate()}>{save.isPending?"Saving…":"Save metadata"}</button><p className="mt-2 text-xs text-faint">Changed fields are stored in the database and protected from rescans.{library.options?.save_nfo?" NFO writeback is enabled.":" NFO writeback is disabled."}</p>
 </footer></div>;
}
