import {Link} from "../lib/libraryNavigation";
import {Images} from "lucide-react";
import {useArtworkPlugin,type ArtworkPluginSettings} from "../lib/artworkPlugin";
import {useEffect,useRef} from "react";
import {useMutation,useQuery,useQueryClient} from "@tanstack/react-query";
import {createPortal} from "react-dom";
import {Server, X} from "lucide-react";
import {apiRequest,api} from "../api/client";
import {ServersSection,DefaultArtworkSourcesFields} from "../pages/SettingsPage";
export interface PluginSettings {enabled:boolean;pinned:boolean}
export function useServerConnectPlugin(){return useQuery({queryKey:["plugin-server-connect"],queryFn:()=>apiRequest<PluginSettings>("/plugins/server-connect")});}
export function ServerConnectPopup({onClose}:{onClose:()=>void}){
 const dialog=useRef<HTMLDialogElement>(null);
 const settings=useServerConnectPlugin();const client=useQueryClient();
 const save=useMutation({mutationFn:(value:PluginSettings)=>apiRequest<PluginSettings>("/plugins/server-connect",{method:"PUT",body:JSON.stringify(value)}),onSuccess:value=>client.setQueryData(["plugin-server-connect"],value)});
 useEffect(()=>{dialog.current?.showModal();},[]);
 return createPortal(<dialog ref={dialog} onCancel={onClose} onClick={event=>{if(event.target===event.currentTarget)onClose();}} aria-label="Server Connect configuration" className="fixed inset-0 m-auto max-h-[85dvh] w-[min(64rem,calc(100vw-2rem))] overflow-y-auto rounded-2xl border border-border bg-sidebar p-6 text-white shadow-2xl backdrop:bg-black/60"><header className="mb-6 flex items-center justify-between"><h2 className="flex items-center gap-2 text-lg font-semibold"><Server className="size-5"/>Server Connect</h2><button aria-label="Close Server Connect" onClick={onClose} className="rounded-lg p-2 text-muted hover:bg-elevated"><X className="size-5"/></button></header>{settings.data&&<div className="mb-6 space-y-4 border-b border-border pb-6">{([['enabled','Enable Server Connect'],['pinned','Pin to Settings']] as const).map(([key,label])=><label key={key} className="flex items-center justify-between text-sm"><span>{label}</span><input role="switch" aria-label={label} type="checkbox" disabled={save.isPending} checked={settings.data![key]} onChange={event=>save.mutate({...settings.data!,[key]:event.target.checked})} className="size-5 accent-accent"/></label>)}<p className="text-xs text-muted">Disabling pauses library metadata and artwork synchronization. Saved connections and mappings are preserved. Pinning only adds a Settings shortcut.</p></div>}{(settings.error||save.error)&&<p role="alert" className="mb-4 text-danger">{(settings.error||save.error)?.message}</p>}<ServersSection/></dialog>,document.body);
}
export default function PluginsPage({open=false,onOpen,onClose,artworkOpen=false,onArtworkOpen}:{open?:boolean;onOpen:()=>void;onClose:()=>void;artworkOpen?:boolean;onArtworkOpen:()=>void}){
 const artwork=useArtworkPlugin();
 const plugin=useServerConnectPlugin();const servers=useQuery({queryKey:["servers"],queryFn:api.listServers});
 return <div className="flex h-full flex-wrap content-start items-stretch gap-5 overflow-y-auto"><button onClick={onOpen} className="w-full max-w-sm shrink-0 rounded-2xl border border-border bg-window p-6 text-left transition-colors hover:border-accent focus-visible:outline-accent"><Server className="mb-4 size-9 text-accent"/><h2 className="text-lg font-semibold">Server Connect</h2><p className="mt-2 text-sm text-muted">Import and synchronize shared metadata and static artwork with connected media servers.</p><p className="mt-4 text-xs text-muted">Built-in · {plugin.data?plugin.data.enabled?"Enabled":"Disabled":"Loading…"} · {servers.data?.length??0} connections</p></button><button onClick={onArtworkOpen} className="w-full max-w-sm shrink-0 rounded-2xl border border-border bg-window p-6 text-left hover:border-accent"><Images className="mb-4 size-9 text-accent"/><h2 className="text-lg font-semibold">Artwork</h2><p className="mt-2 text-sm text-muted">Browse, upload, remove, and edit artwork with PosterEdit and BackdropEdit.</p><p className="mt-4 text-xs text-muted">Built-in · {artwork.data?.enabled === false ? "Disabled" : "Enabled"}</p></button>{artworkOpen&&<ArtworkPopup onClose={onClose}/>} {open&&<ServerConnectPopup onClose={onClose}/>}</div>;
}

export function ArtworkPopup({onClose}:{onClose:()=>void}){
 const dialog=useRef<HTMLDialogElement>(null);const settings=useArtworkPlugin();const client=useQueryClient();
 const save=useMutation({mutationFn:(value:ArtworkPluginSettings)=>apiRequest<ArtworkPluginSettings>("/plugins/artwork",{method:"PUT",body:JSON.stringify(value)}),onSuccess:value=>client.setQueryData(["plugin-artwork"],value)});
 useEffect(()=>{dialog.current?.showModal();},[]);
 return createPortal(<dialog ref={dialog} onCancel={onClose} onClick={event=>{if(event.target===event.currentTarget)onClose();}} aria-label="Artwork configuration" className="fixed inset-0 m-auto max-h-[85dvh] w-[min(52rem,calc(100vw-2rem))] overflow-y-auto rounded-2xl border border-border bg-sidebar p-6 text-white shadow-2xl backdrop:bg-black/60"><header className="mb-6 flex items-center justify-between"><h2 className="flex items-center gap-2 text-lg font-semibold"><Images className="size-5"/>Artwork</h2><button aria-label="Close Artwork" onClick={onClose} className="rounded-lg p-2 text-muted hover:bg-elevated"><X className="size-5"/></button></header>{settings.data&&<div className="space-y-5">{([['enabled','Enable Artwork'],['pinned','Pin to Settings'],['poster_edit','Enable PosterEdit'],['backdrop_edit','Enable BackdropEdit']] as const).map(([key,label])=><label key={key} className="flex items-center justify-between text-sm"><span>{label}</span><input type="checkbox" role="switch" aria-label={label} checked={settings.data![key]} disabled={save.isPending} onChange={event=>save.mutate({...settings.data!,[key]:event.target.checked})} className="size-5 accent-accent"/></label>)}<p className="border-b border-border pb-5 text-xs text-muted">Disabling hides artwork tools and pauses automatic artwork downloads. Existing artwork remains visible and metadata fetching continues.</p><DefaultArtworkSourcesFields flat/><Link to="/settings/sources" onClick={onClose} className="inline-block rounded-full border border-border px-4 py-2 text-sm">Manage Search Providers</Link></div>}{(settings.error||save.error)&&<p role="alert" className="text-danger">{(settings.error||save.error)?.message}</p>}</dialog>,document.body);
}
