import {useState} from "react";
import {useQuery,useMutation,useQueryClient} from "@tanstack/react-query";
import {apiRequest} from "../api/client";
export interface MaintenanceTask {running?:boolean;id:string;title:string;description:string;enabled:boolean;interval_days:number;retention_days:number;cleanup_artwork:boolean;cleanup_placeholders?:boolean;cleanup_cache:boolean;cleanup_records?:boolean;cleanup_reader?:boolean;cleanup_temporary:boolean;last_run:number;last_result:string;}
interface Report {records?:number;placeholders?:number;files:number;bytes:number;result:string;}
const button="rounded-full border border-border bg-input px-4 py-2 text-sm text-white hover:border-accent disabled:opacity-50";
export default function ScheduledTasks(){
 const client=useQueryClient();
 const [cacheMessage,setCacheMessage]=useState("");
 const clearCache=useMutation({mutationFn:()=>apiRequest<Report>("/tasks/provider-cache",{method:"DELETE"}),onSuccess:data=>{setCacheMessage(data.result);void client.invalidateQueries({predicate:q=>["artwork","artwork-search","posterdb-search","posterdb-set","anidb-identify-poster"].includes(String(q.queryKey[0]))});}});
 const tasks=useQuery({queryKey:["scheduled-tasks"],queryFn:()=>apiRequest<MaintenanceTask[]>("/tasks"),refetchInterval:30000});
 return <section className="space-y-5 pb-6"><p className="text-sm text-muted">Run maintenance now or enable a recurring schedule. Schedules run while PosterView is running; overdue tasks run when it starts.</p>{tasks.isPending&&<p role="status">Loading tasks…</p>}{tasks.error&&<p role="alert">{tasks.error.message}</p>}{tasks.data?.map(task=><TaskCard key={`${task.id}:${JSON.stringify(task)}`} task={task}/>)}<div className="space-y-3 rounded-xl border border-border bg-window p-5"><h2 className="font-semibold">Troubleshooting</h2><p className="text-sm text-muted">Provider results and images are cached automatically for up to 30 days, with a 250 MB limit per cache. Clear them to troubleshoot outdated results. Applied artwork and media files are preserved.</p><button className={button} disabled={clearCache.isPending||tasks.data?.some(t=>t.running)} onClick={()=>{if(window.confirm("Clear cached provider results and images? They will be downloaded again when needed. Applied artwork and media files are preserved."))clearCache.mutate();}}>{clearCache.isPending?"Clearing…":"Clear provider cache"}</button>{cacheMessage&&<p role="status" className="text-sm text-muted">{cacheMessage}</p>}{clearCache.error&&<p role="alert">{clearCache.error.message}</p>}</div></section>;
}
function TaskCard({task}:{task:MaintenanceTask}){
 const client=useQueryClient();const [draft,setDraft]=useState(task);const [report,setReport]=useState<Report|null>(null);const [message,setMessage]=useState("");
 const save=useMutation({mutationFn:()=>apiRequest<MaintenanceTask[]>(`/tasks/${task.id}`,{method:"PUT",body:JSON.stringify(draft)}),onSuccess:data=>{client.setQueryData(["scheduled-tasks"],data);}});
 const run=useMutation({mutationFn:()=>apiRequest<Report>(`/tasks/${task.id}/run`,{method:"POST"}),onSuccess:data=>{setMessage(data.result);setReport(null);void client.invalidateQueries({queryKey:["scheduled-tasks"]});}});
 const preview=useMutation({mutationFn:()=>apiRequest<Report>("/tasks/cleanup/preview"),onSuccess:setReport});
 const dirty=JSON.stringify(draft)!==JSON.stringify(task);const busy=save.isPending||run.isPending||preview.isPending;
 return <article className="space-y-4 rounded-xl border border-border bg-window p-5"><div><h2 className="font-semibold">{task.title}</h2><p className="mt-1 text-sm text-muted">{task.description}</p><p className="mt-3 text-xs text-muted">{task.running?"Running":task.enabled?`Scheduled every ${task.interval_days} days`:"Manual run only"}</p></div><details className="rounded-lg border border-border"><summary className="cursor-pointer px-4 py-3 text-sm font-medium">Configure {task.title}</summary><div className="space-y-4 border-t border-border p-4">
 <div className="flex flex-wrap items-center gap-5"><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={draft.enabled} onChange={e=>setDraft({...draft,enabled:e.target.checked})}/>Enable schedule for {task.title}</label><label className="text-sm">Every <input aria-label={`${task.title} interval days`} className="mx-2 w-16 rounded border border-border bg-input p-2" type="number" min={1} max={365} value={draft.interval_days} onChange={e=>setDraft({...draft,interval_days:Number(e.target.value)})}/> days</label>{task.id!=="database"&&<label className="text-sm">Keep for <input aria-label={`${task.title} retention days`} className="mx-2 w-20 rounded border border-border bg-input p-2" type="number" min={1} max={3650} value={draft.retention_days} onChange={e=>setDraft({...draft,retention_days:Number(e.target.value)})}/> days</label>}</div>
 {task.id==="cleanup"&&<><div className="flex flex-wrap gap-5 text-sm">{[["cleanup_placeholders","Hidden missing-file placeholders"],["cleanup_artwork","Unused managed artwork"],["cleanup_cache","Expired provider and local artwork caches"],["cleanup_records","Removed-library and item sync records"],["cleanup_reader","Deleted-file reader data (progress and bookmarks)"],["cleanup_temporary","Abandoned temporary files"]].map(([key,label])=><label key={key} className="flex items-center gap-2"><input type="checkbox" checked={draft[key as "cleanup_artwork"] ?? true} onChange={e=>{setReport(null);setDraft({...draft,[key]:e.target.checked});}}/>{label}</label>)}</div><p className="text-xs text-muted">Unused artwork starts its retention period when first detected by cleanup. Hidden missing-file placeholders can be removed after retention expires. Their artwork is removed only when unused elsewhere. Saved edits, backups, and other referenced images are protected. Cleanup never touches media folders. Deleted-file reader cleanup removes all progress and bookmarks for confirmed deleted books; unavailable folders are skipped.</p></>}
 </div></details>
 <p className="text-xs text-muted">Last run: {task.last_run?new Date(task.last_run*1000).toLocaleString():"Never"}{task.enabled&&` · Next due: ${task.last_run?new Date((task.last_run+task.interval_days*86400)*1000).toLocaleString():"At the next scheduler check"}`}</p>{(message||task.last_result)&&<p role="status" className="text-sm text-muted">{message||task.last_result}</p>}
 <div className="flex flex-wrap gap-3">{dirty&&<button className={button} disabled={busy||draft.interval_days<1||draft.retention_days<1} onClick={()=>save.mutate()}>Save task</button>}{task.id==="cleanup"?<button className={button} disabled={dirty||busy} onClick={()=>preview.mutate()}>Review cleanup</button>:<button className={button} disabled={dirty||busy} onClick={()=>run.mutate()}>{run.isPending?"Running…":"Run now"}</button>}</div>
 {dirty&&<p className="text-xs text-muted">Save changes before running this task.</p>}
 {report&&<div className="space-y-3 border-t border-border pt-3"><p className="text-xs text-muted">Artwork eligibility is checked again after obsolete records and hidden placeholders are removed.</p><p>{report.records??0} obsolete records · {report.placeholders??0} hidden placeholders · {report.files} eligible files · {(report.bytes/1024/1024).toFixed(1)} MB</p><button className={button} disabled={dirty||busy||(!report.files&&!report.placeholders&&!report.records)} onClick={()=>run.mutate()}>{run.isPending?"Cleaning…":"Clean selected"}</button></div>}
 {(save.error||run.error||preview.error)&&<p role="alert" className="text-sm text-danger">{(save.error||run.error||preview.error)?.message}</p>}
 </article>;
}
