import {Switch} from "./ui";
import {useState} from "react";
import {nativeLibraries,type NativeLibrary,type NativeCatalogEntry} from "../api/nativeLibraries";
export default function SeriesActionsDialog({action,library,entry,entries,onSaved}:{action:string;library:NativeLibrary;entry:NativeCatalogEntry;entries:NativeCatalogEntry[];onSaved:()=>void}){
 const [busy,setBusy]=useState(false),[error,setError]=useState("");
 const [mode,setMode]=useState("replace"),[replaceImages,setReplaceImages]=useState(false);
 const missing=entries.filter(e=>e.path.startsWith(`${entry.path}/`) && e.metadata.missing===true && e.kind!=="season" && (library.options?.show_missing_specials===true || Number(e.metadata.season)!==0));
 async function apply(){setBusy(true);setError("");try{if(action==="remove-identification"){const result=await nativeLibraries.editItem(library.id,entry,{identifiers:{}});if(result.warnings.length)throw new Error(result.warnings.join(" · "));}else await nativeLibraries.scanFolder(library.id,entry.id,true,{replaceMetadata:mode==="replace",replaceImages});onSaved();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 if(action==="refresh-metadata")return <div className="flex min-h-[26rem] flex-col"><div className="flex-1 space-y-6 p-6"><label className="block text-sm font-medium">Refresh mode<select aria-label="Refresh mode" disabled={busy} value={mode} onChange={e=>setMode(e.target.value)} className="mt-2 w-full rounded-lg border border-border bg-input px-3 py-2"><option value="replace">Replace all metadata</option><option value="missing">Search for missing metadata</option></select></label><p className="text-xs text-muted">{mode==="replace"?"Replace descriptive metadata, including manual edits, using this library's enabled providers and current IDs. File details and numbering are kept.":"Fill missing fields using the current IDs. Existing metadata and manual edits are kept."}</p><div className="flex items-center justify-between gap-4"><span className="text-sm font-medium">Replace existing images</span><Switch label="Replace existing images" checked={replaceImages} disabled={busy} onChange={()=>setReplaceImages(!replaceImages)}/></div><p className="text-xs text-muted">Download replacement static images using TVDB only for series, movies, and anime. Book libraries use their configured image providers. Matching local images will be overwritten. Existing images are kept if no replacement is available; animations are preserved.</p>{library.library_type!=="books"&&<><div className="flex items-center justify-between gap-4"><span className="text-sm font-medium text-muted">Replace existing video preview thumbnails</span><Switch label="Replace existing video preview thumbnails" checked={false} disabled onChange={()=>{}}/></div><p className="text-xs text-muted">Unavailable: PosterView does not currently generate video preview thumbnails.</p></>}{error&&<p role="alert" className="text-danger">{error}</p>}</div><footer className="bg-sidebar p-6"><button disabled={busy} className="w-full rounded-full bg-accent px-4 py-2.5 text-sm font-medium text-base disabled:opacity-50" onClick={()=>void apply()}>{busy?"Refreshing…":"Refresh"}</button></footer></div>;
 return <div className="space-y-4 p-6">{action==="missing-files"?<><p className="text-sm text-muted">Missing files discovered from the current provider metadata.</p>{missing.map(e=><div key={e.id} className="border-b border-border py-3"><p className="font-medium">{e.title}</p><p className="text-xs text-muted">{e.kind==="episode"?`Season ${e.metadata.season} · Episode ${e.metadata.episode}`:e.metadata.volume!=null?`Volume ${e.metadata.volume}`:`Chapter ${e.metadata.chapter}`}</p><p className="mt-1 text-sm text-muted">{String(e.metadata.plot??"")}</p></div>)}{!missing.length&&<p>No missing files found. Scan this series to discover missing files.</p>}</>:<><p className="text-sm">{action==="remove-identification"?"Remove the provider IDs for this item? Descriptive metadata, artwork, and media files will be kept.":"Fetch missing metadata using the current identity and configured providers. Existing metadata and manually edited fields will be kept."}</p><button disabled={busy} className="rounded-lg border border-border px-4 py-2 disabled:opacity-50" onClick={()=>void apply()}>{busy?"Working…":action==="remove-identification"?"Remove identification":"Refresh metadata"}</button></>}{error&&<p role="alert" className="text-danger">{error}</p>}</div>;
}
