import {SERVER_CONNECT_AVAILABLE} from "../lib/serverConnectPlugin";
import {useQueries,useQuery} from "@tanstack/react-query";
import {Link} from "react-router-dom";
import {Server,Activity,AlertCircle} from "lucide-react";
import {api,apiRequest} from "../api/client";
import {nativeLibraries} from "../api/nativeLibraries";
import NativeScanProgress from "./NativeScanProgress";
import SettingsPageFrame,{SETTINGS_BUTTON} from "./SettingsPageFrame";
import type {MaintenanceTask} from "./ScheduledTasks";
export function groupNotices(notices:{library:string;message:string}[]){
 const groups=new Map<string,{library:string;summary:string;messages:string[]}>();
 for(const notice of notices){const separator=notice.message.lastIndexOf(": ");const summary=separator<0?notice.message:notice.message.slice(separator+2);const key=JSON.stringify([notice.library,summary]);const group=groups.get(key)??{library:notice.library,summary,messages:[]};if(!group.messages.includes(notice.message))group.messages.push(notice.message);groups.set(key,group);}
 return [...groups.values()];
}
export default function ServerSettingsDashboard(){
 const info=useQuery({queryKey:["server-runtime-status"],queryFn:()=>apiRequest<{name:string;version:string;backend:string;data_dir:string}>("/status"),refetchInterval:30000});
 const libraries=useQuery({queryKey:["native-libraries"],queryFn:nativeLibraries.list});
 const servers=useQuery({queryKey:["servers"],queryFn:api.listServers,enabled:SERVER_CONNECT_AVAILABLE});
 const tasks=useQuery({queryKey:["scheduled-tasks"],queryFn:()=>apiRequest<MaintenanceTask[]>("/tasks"),refetchInterval:5000});
 const scans=useQueries({queries:(libraries.data??[]).map(l=>({queryKey:["native-scan",l.id],queryFn:()=>nativeLibraries.status(l.id),refetchInterval:5000}))});
 const syncs=useQueries({queries:(libraries.data??[]).map(l=>({queryKey:["native-sync",l.id],queryFn:()=>nativeLibraries.syncStatus(l.id),enabled:SERVER_CONNECT_AVAILABLE && !!l.options?.server_sync?.enabled,refetchInterval:5000}))});
 const notices=groupNotices((libraries.data??[]).flatMap((l,i)=>[...(scans[i]?.data?.warnings??[]),...(SERVER_CONNECT_AVAILABLE ? syncs[i]?.data?.notices??[] : [])].map(message=>({library:l.name,message}))));
 const panel="rounded-xl border border-border bg-window p-5";
 const loading= libraries.isPending||scans.some(q=>q.isPending)||syncs.some((q,i)=>libraries.data?.[i]?.options?.server_sync?.enabled&&SERVER_CONNECT_AVAILABLE&&q.isPending);
 const unavailable=libraries.isError||scans.some(q=>q.isError)||syncs.some((q,i)=>libraries.data?.[i]?.options?.server_sync?.enabled&&SERVER_CONNECT_AVAILABLE&&q.isError);
 return <SettingsPageFrame title="Dashboard" description="Server information, current activity, and libraries needing attention."><div className="grid gap-5 lg:grid-cols-2">
 <section className={`${panel} lg:col-span-2`}><h2 className="mb-4 flex items-center gap-2 text-lg font-semibold"><Server className="size-5"/>PosterView Server</h2>{info.isPending&&<p role="status">Loading server information…</p>}{info.error&&<p role="alert" className="text-danger">{info.error.message}</p>}{info.data&&<dl className="grid gap-4 text-sm sm:grid-cols-3">{[["Version",info.data.version],["Access address",window.location.origin],["Application data",info.data.data_dir]].map(([label,value])=><div key={label}><dt className="text-muted">{label}</dt><dd className="mt-1 break-all">{value}</dd></div>)}</dl>}<div className="mt-5 flex flex-wrap gap-3"><Link to="/settings/libraries" className={SETTINGS_BUTTON}>{libraries.data?.length??0} libraries</Link>{SERVER_CONNECT_AVAILABLE && <Link to="/settings/servers" className={SETTINGS_BUTTON}>{servers.data?.length??0} server connections</Link>}</div></section>
 <section className={panel}><h2 className="mb-4 flex items-center gap-2 text-lg font-semibold"><Activity className="size-5"/>Activity</h2>{libraries.error&&<p role="alert" className="text-danger">{libraries.error.message}</p>}{libraries.isPending&&<p role="status">Loading libraries…</p>}{libraries.data?.length===0&&<Link to="/settings/libraries" className="text-accent">Add your first library</Link>}<div className="divide-y divide-border">{libraries.data?.map((library,i)=>{const scan=scans[i]?.data;const sync=SERVER_CONNECT_AVAILABLE ? syncs[i]?.data : undefined;return <div key={library.id} className="py-3 first:pt-0"><div className="flex items-center justify-between gap-3"><Link to={`/media/${encodeURIComponent(library.id)}`} className="font-medium hover:text-accent">{library.name}</Link><span className="text-xs text-muted">{scan?.status.replaceAll("_"," ")??"Checking…"}</span></div>{scan?.status==="scanning"&&<div className="mt-2"><NativeScanProgress status={{...scan,show_progress:true}} compact/></div>}{sync&&<p className="mt-2 text-xs text-muted">Server sync: {sync.status} · {sync.pending} pending · {sync.failed} failed</p>}{scans[i]?.error&&<p className="mt-2 text-xs text-danger">{scans[i].error!.message}</p>}{SERVER_CONNECT_AVAILABLE && library.options?.server_sync?.enabled&&syncs[i]?.error&&<p className="mt-2 text-xs text-danger">{syncs[i].error!.message}</p>}</div>;})}</div><div className="mt-4 border-t border-border pt-4"><Link to="/settings/tasks" className="text-sm hover:text-accent">Scheduled tasks</Link>{tasks.error&&<p role="alert" className="mt-2 text-xs text-danger">{tasks.error.message}</p>}{tasks.data?.map(task=><p key={task.id} className="mt-2 flex justify-between gap-3 text-xs text-muted"><span>{task.title}</span><span>{task.running?"Running":task.last_result.startsWith("Failed:")?"Needs attention":task.enabled?"Scheduled":"Manual"}</span></p>)}</div></section>
 <section className={panel}><h2 className="mb-4 flex items-center gap-2 text-lg font-semibold"><AlertCircle className="size-5"/>Needs attention</h2>{!notices.length&&<p className="text-sm text-muted">{unavailable?"Some library statuses are unavailable.":loading?"Checking library notices…":"No library notices reported."}</p>}<div className="divide-y divide-border">{notices.map(group=><details key={JSON.stringify([group.library,group.summary])} className="py-3 first:pt-0"><summary className="cursor-pointer text-sm"><span className="font-medium">{group.library}</span><span className="ml-2 text-xs text-muted">{group.messages.length} {group.messages.length===1?"notice":"notices"}</span><span className="mt-1 block text-muted">{group.summary}</span></summary><div className="mt-3 space-y-2 border-l border-border pl-3">{group.messages.map(message=><p key={message} className="break-words text-xs text-muted">{message}</p>)}<Link to="/settings/libraries" className="inline-block text-xs text-accent">Manage library</Link></div></details>)}</div></section>
 </div></SettingsPageFrame>;
}
