import {Switch} from "./ui";
import {useState} from "react";
import {ArrowLeft,Loader2,ImageOff} from "lucide-react";
import {nativeLibraries,type NativeLibrary,type NativeCatalogEntry,type IdentificationCandidate} from "../api/nativeLibraries";
import {SETTINGS_BUTTON} from "./SettingsPageFrame";
const input="mt-2 w-full rounded-lg border border-border bg-input px-3 py-2.5 text-sm text-white";
export default function TVIdentifyPanel({library,entry,busy,onSaved}:{library:NativeLibrary;entry:NativeCatalogEntry;busy:boolean;onSaved:()=>void}){
 const [title,setTitle]=useState(entry.path.split('/').pop()?.replace(/\s*\((19|20)\d{2}\)$/,"")??entry.title);
 const [year,setYear]=useState("");const [imdb,setImdb]=useState("");const [tmdb,setTmdb]=useState("");const [tvdb,setTvdb]=useState("");
 const [step,setStep]=useState<"search"|"results"|"confirm">("search");const [results,setResults]=useState<IdentificationCandidate[]>([]);const [selected,setSelected]=useState<IdentificationCandidate|null>(null);
 const [working,setWorking]=useState(false);const [error,setError]=useState("");const [notice,setNotice]=useState("");const [replace,setReplace]=useState(false);const [applied,setApplied]=useState(false);
 async function search(){setWorking(true);setError("");try{const response=await nativeLibraries.identifySearch(library.id,entry.id,title,year?Number(year):null,{provider:"tvdb",tvdb_id:tvdb.trim()||undefined,imdb_id:imdb.trim()||undefined,tmdb_id:tmdb.trim()||undefined});const group=response.groups.find(g=>g.provider==="tvdb");if(group?.error)throw new Error(group.error);setResults(group?.results??[]);setStep("results");}catch(e){setError((e as Error).message);}finally{setWorking(false);}}
 async function apply(){if(!selected)return;setWorking(true);setError("");try{const result=await nativeLibraries.identify(library.id,entry.id,{revision:entry.revision,title:selected.title,year:selected.year,identifiers:{tvdb:selected.id},rewrite_metadata:true,replace_artwork:replace});if(result.warnings.length){setNotice(result.warnings.join(" "));setApplied(true);}else onSaved();}catch(e){setError((e as Error).message);}finally{setWorking(false);}}
 return <div className="flex h-full min-h-0 flex-col"><div className="min-h-0 flex-1 space-y-5 overflow-y-auto px-6 pb-5 sm:px-8">
 {step!=="search"&&!applied&&<button className={SETTINGS_BUTTON} disabled={working} onClick={()=>{setError("");setStep(step==="confirm"?"results":"search");}}><ArrowLeft className="size-4"/>Back</button>}
 {step==="search"&&<form id="tv-identify-search" className="mx-auto max-w-2xl space-y-5" onSubmit={e=>{e.preventDefault();void search();}}><p className="text-sm text-muted">Enter one or more search criteria. Remove criteria to increase search results.</p><div className="text-sm"><p className="font-medium">Path</p><p className="mt-1 break-all text-muted">/media/{entry.path}</p></div><label className="block text-sm">Title<input aria-label="Identification title" className={input} value={title} onChange={e=>setTitle(e.target.value)} maxLength={200}/></label><label className="block text-sm">Year<input aria-label="Identification year" className={input} value={year} type="number" min={1800} max={2200} onChange={e=>setYear(e.target.value)}/></label>{[["IMDb ID",imdb,setImdb,"https://www.imdb.com"],["TheMovieDB ID",tmdb,setTmdb,"https://www.themoviedb.org"],["TheTVDB ID",tvdb,setTvdb,"https://www.thetvdb.com"]].map(([label,value,setter,url])=><label key={String(label)} className="block text-sm">{String(label)}<input aria-label={String(label)} className={input} value={String(value)} onChange={e=>(setter as (value:string)=>void)(e.target.value)}/><a href={String(url)} target="_blank" rel="noreferrer" className="mt-2 inline-block text-xs text-accent">{String(url)}</a></label>)}</form>}
 {step==="results"&&<section aria-label="TheTVDB matches"><p className="mb-4 text-sm text-muted">Select the correct TVDB series.</p>{!results.length?<p className="text-sm text-muted">No matching series. Go back and remove the year or try a shorter title.</p>:<div className="grid grid-cols-2 gap-4 sm:grid-cols-3 lg:grid-cols-4">{results.map(candidate=><button key={candidate.id} className="min-w-0 text-left focus-visible:outline focus-visible:outline-2 focus-visible:outline-accent" onClick={()=>{setSelected(candidate);setReplace(false);setStep("confirm");}}><TVPoster candidate={candidate}/><p className="mt-2 line-clamp-2 text-sm font-medium">{candidate.title}</p><p className="mt-1 text-xs text-muted">{candidate.year??"Unknown year"}</p></button>)}</div>}</section>}
 {step==="confirm"&&selected&&<section className="mx-auto max-w-2xl space-y-5"><div className="flex items-center gap-5"><div className="w-32 shrink-0"><TVPoster candidate={selected}/></div><div><h3 className="text-lg font-semibold">{selected.title}</h3><p className="mt-1 text-sm text-muted">{selected.year??"Unknown year"} · TheTVDB</p><p className="mt-2 text-xs text-muted">TVDB ID {selected.id}</p></div></div><p className="text-sm text-muted">Replace all existing descriptive metadata with this TVDB match? Previous metadata and IDs, including manual edits, will be cleared. Season and episode metadata will be refreshed. File details and numbering remain.</p><div className="flex items-center justify-between gap-4 text-sm"><span>Replace existing artwork</span><Switch label="Replace existing artwork" checked={replace} disabled={working||applied} onChange={()=>setReplace(!replace)}/></div><p className="text-xs text-muted">{replace?"Downloads available images from TVDB and replaces matching local images. Other images are written to media folders when library artwork saving is enabled.":"Existing artwork will be kept."} The search poster is a preview; downloaded artwork may differ.</p></section>}
 {busy&&<p className="text-xs text-muted">Wait for the library scan to finish before replacing metadata.</p>}{error&&<p role="alert" className="text-sm text-danger">{error}</p>}{notice&&<p role="status" className="text-sm text-muted">{notice}</p>}</div><footer className="flex shrink-0 items-center gap-3 border-t border-border bg-sidebar px-6 py-4 sm:px-8">{step==="search"?<button type="submit" form="tv-identify-search" className={`${SETTINGS_BUTTON} w-full`} disabled={working||(!title.trim()&&!tvdb.trim()&&!tmdb.trim()&&!imdb.trim())}>{working&&<Loader2 className="size-4 animate-spin"/>}Search</button>:step==="confirm"?<button className={`${SETTINGS_BUTTON} w-full`} disabled={busy||working} onClick={()=>applied?onSaved():void apply()}>{working&&<Loader2 className="size-4 animate-spin"/>}{applied?"Done":"Replace metadata"}</button>:<span className="text-xs text-muted">Results from TheTVDB</span>}</footer></div>;
}
function TVPoster({candidate}:{candidate:IdentificationCandidate}){const [failed,setFailed]=useState(false);return <div className="aspect-[2/3] overflow-hidden rounded-xl bg-input">{candidate.poster&&!failed?<img src={candidate.poster} alt="" loading="lazy" className="size-full object-cover" onError={()=>setFailed(true)}/>:<div className="grid size-full place-items-center text-muted"><ImageOff className="size-8"/></div>}</div>;}
