[package]
name = "posterview-infra-media-servers"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
base64.workspace = true
chrono.workspace = true
posterview-contracts.workspace = true
posterview-url-security.workspace = true
reqwest.workspace = true
serde_json.workspace = true

[lints]
workspace = true

[dev-dependencies]
axum.workspace = true
tokio.workspace = true
